sudo: required


dist: bionic

language: python

python:
    - "3.8"

cache:
    - pip

before_install:
    - sudo apt-get update
    - sudo apt-get install parallel fonts-noto-cjk
    - ditaa -h || true

install:
    - pip install 'pelican'
    - pip install jinja2 py3babel babel beautifulsoup4 markdown
    - sudo locale-gen zh_HK.UTF-8
    - locale -a
    - pelican --version

script:
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - git config --global push.default simple
    - git clone --depth 1 https://github.com/farseerfc/pelican-plugins plugins
    - git clone --depth 1 https://$GH_TOKEN@github.com/farseerfc/sak.uy output
    - make html
    - ./renderpdf.sh
    - env SITEURL="sak.uy" make publish

after_success:
    - cd output
    - git add -A .
    - git commit -m "update from travis"
    - git push --quiet

